### ISSUE TITLE
Enhanced data logging, "Track Changes" feature

### ISSUE THREAD

**Issue by Automate1** [opensourceautomation/Open-Source-Automation#114]
Currently all properties are logged into a string field regardless of their data type. We need to separate the different data types such as Float, Integer and Boolean into different field types for more efficient retrieval of information like monthly averages and total device ON time.

**Comment by VaughnRupp** [comment]
The approach I am going to use will leave the existing property_value string, but will replicate the value into the correct field type so it is available for analytics.    Analytics will have to look at the data_type to figure out which field to use, where general/api queries will look at the existing field so they will not be affected.

**Comment by VaughnRupp** [comment]
This is done finally and working well so far.   I changed the storage to use the appropriate fiends and then modified the propert history view to select the right underlying field, so you are always looking at Property_Value, but that is really just the alias for the correct field name.    

Finally closing this issue!
