### ISSUE TITLE
Start and Stop the UltiDev web site with OSA Web plugin Start/Stop

### ISSUE THREAD

**Issue by Automate1** [opensourceautomation/Open-Source-Automation#205]
This will make it possible for the web site to be upgraded with a new plugin like all the other plugins.

More info here
http://www.opensourceautomation.com/phpBB3/web-site-upgrades-t957.html

**Comment by VaughnRupp** [comment]
Updated the Webserver plugin to check for and start/stop the UWS services.

**Comment by VaughnRupp** [comment]
ok, I found this to be unbearable.   I want to use the website even if the service is stopped.   Can we just make the plugin code stop it or something?

**Comment by Automate1** [comment]
The OSA web server can be restarted using the UltiDev Web Server Explorer at any time.

It also would be handy to add a web server start/stop button on the OSA Manager app.  This way you could start the web server from the same app you use to stop the OSA service.

**Comment by VaughnRupp** [comment]
yeah, a separate button would be fine.   Shutting it down with the main service every time is painful (but works).   Stopping UWS kills your sessions, but pages were not coded to reload if they lose session, but keep a cookie, so then I have to change the url manually to force a relog to get a new session.   I also like to clear the logs before I start the service, but once you stop the service, the web page dies, so I can't issue the clear logs, etc.  
I will move the code to a separate button that is only visible is UWS is installed.

**Comment by VaughnRupp** [comment]
Manager has been modified to monitor and control the UWS server, just like the main service.   A future iteration maybe would allow it to work with IIS and others in a configurable manner.   This is working good though,
