### ISSUE TITLE
GUI - Add resize functionality

### ISSUE THREAD

**Issue by VaughnRupp** [opensourceautomation/Open-Source-Automation#207]
GUI lost resize ability when converted to WPF.   Not sure if it is due to graphics being moved to the DB or what.    So I will just experiment with added it back in and see how it goes.

**Comment by KHerron** [comment]
Yea, I don;t see that any more either. However, I think I can fix this fairly easily. I can even add it to the Add/Edit screen so it can be done from within the screens application.

**Comment by VaughnRupp** [comment]
Oh yay, this is done!
