### ISSUE TITLE
Web UI - Edit Items/Labels in property List

### ISSUE THREAD

**Issue by Automate1** [opensourceautomation/Open-Source-Automation#217]
Add the ability to edit existing Items and Labels in the property List popup.  Also the ability to change their order in the list.

**Comment by VaughnRupp** [comment]
Since that popup grid is just 2 test fields, in-grid editing makes sense, so I will try to know that out.   As far as changing the order, you can use the Item for the index and Label for your data and the Item would hold the order.    But then editing or changing the order would be hard unless I add a up/down button in the grid, which I will also try.   I will add a hidden index column if needed.

**Comment by VaughnRupp** [comment]
OK, this thing was in worse shape then I thought.   I assumed you were talking about In-Grid edit, but the update button was not even enabled, so now I take it you were just asked for basic editing like most other grids.    In testing, the bottom text boxes never even populate.    So I will make it so when you click on a row, the bottom boxes populate and can change a value and click save.

**Comment by VaughnRupp** [comment]
Good lord. 30 minutes of trying to work on asp.net and I want to slice my wrists =)   
The worst thing is when debugging objects.aspx is when you select any property, it locks up the interface until you click save on the property.   It does not do that when running the page from the actual web server.   
It looks like the property list grid needs to call a postback like the other grids to update the text boxes.   I don't want to hose the page up and worse than it is, so I am going to pass on this issue for now.

**Comment by VaughnRupp** [comment]
I finally fixed the editing on the Property list Editor.    Tested Add, Update and Delete.

**Comment by VaughnRupp** [comment]
The list was unsorted at all, so if you added an entry starting with "a", it would show up at the bottom.   I made the list alphabetical now so it is more intuitive.    I am not sure it is worth the trouble to make it reverse sortable, etc, so I am closing this ticket.
