### ISSUE TITLE
Get rid of Manager and replace with simple utility

### ISSUE THREAD

**Issue by bwoodworth** [opensourceautomation/Open-Source-Automation#233]
The Manager is not longer needed.  We need to replace wit with a simple utility that will allows for starting and stopping the service and run any executed windows commands. Plugin installing and control will all happen withing the web UI.

**Comment by VaughnRupp** [comment]
Here is where we are for 048:
Manager has become that simple utility that just starts and stops the local service.   Manager had a UDP listener that handles the Service's ON/OFF methods for remote control.   You can only remote control the client services though.    And the services handle 100% of the plugins and manager has Nothing to do with them anymore.   The Services have their own UDP type separate from manager to sort out these broadcasts.   

Not only was Manager simplified, but all Plugin pages are gone now, and just standard OSA objects handle all the plugins.   With proper usage of Containers, Computer Name is now gone too.   Basically every client has a name appended for that computer and none of the primary service's plugins do...
