### ISSUE TITLE
Screens App - State Images need to be able to select methods for the clicks.

### ISSUE THREAD

**Issue by VaughnRupp** [opensourceautomation/Open-Source-Automation#235]
You can choose custom states to represent with the Images, but not what to do when you click on the image.   It currently only supports on and off.

**Comment by KHerron** [comment]
I can work on this too.

**Comment by VaughnRupp** [comment]
This can be a little confusing, because some objects do not have methods, so you could be selecting a method, or you could be selecting a state.   If there are methods available, do you even give them the option of picking a state?   I want to ponder it just a bit more since it has pretty big impact.

**Comment by VaughnRupp** [comment]
I just don't have enough examples in my head of things using states for other things than On/Off too.   The only once I know of is SYSTEM, and Thermostat.    And even them, I ponder if it is not best to switch them to ON/OFF.   SYSTEM ON/OFF would be tied to the service, and the Mode (Home,Away,Sleep,etc) could be a property on system.   Same with Thermostat, I don't like the Heat/Cool options being used in the State.   The A/C unit is running or it is not, what mode it is in should be a property, not a state.    Argh...

**Comment by KHerron** [comment]
I totally agree with you!

 

I have been creating a few more Custom Controls, and one of them is an LED Slider that can be used on ANY object that has an Integer Property.

You will also be able to select up to 3 different methods, and it can also show the objects state. 

I’m testing using an X-10 Dimmer, and setting it to the “Level” property and running the “ON” method with the slider value as Param1.

 

As I was playing around I noticed that the only 2 objects that DO NOT use ON/OFF is the SYSTEM and THERMOSTAT.

So, yes, I totally agree all objects should be uniform.

As you said, it doesn’t matter Heat or AC, is either On or it’s not.

**Comment by VaughnRupp** [comment]
I enhanced the method code so it does not set a state if a matching method is found, and I also read in the default parameters to use with the method, but selecting a method other than the matching state is not going to happen.   The Click Image control can perform that feature.   We used to have a Method Image, which got replaced by the click image.   Click Image will not change image based on state though, so there may be some kinda of need, but for now I am closing this issue.

**Comment by KHerron** [comment]
Very Good!

 

Also, on the Click Image, have you tested the Parameter Input screen?

This is done by setting one of the parameter on the method to “[ASK]”.

 

Then when you click, a popup will ask you for the parameter.

 

I think the last time I tested it was back on 4.4 and it did not work.

I think I remember fixing it, but not sure if it ever did.

 

Will test that this weekend too.
