### ISSUE TITLE
WEB UI - click and State controls need to be implemented

### ISSUE THREAD

**Issue by VaughnRupp** [opensourceautomation/Open-Source-Automation#238]
Since the WebUI does not reuse our WPF controls, the functionilty of the Screen controls needs to be duplicated on the WebUI controls.    Which is Mouse Up/Down features on the Click Control, and Animation on the State Control

**Comment by KHerron** [comment]
I am willing to work on this. I have gotten to know this part very well, here lately.

Would you like to see the same Add/Edit functionality also?

**Comment by KHerron** [comment]
Looking in to the Javascript required to solve this now!

**Comment by KHerron** [comment]
OK, I now have the "Press" and "Release" (mouseUp/mouseDown) methods working in the WebUI. I have even implemented the "Press" and "Release" image change to work too!

However, I noticed in the screens application: "ClickImage", the code for the Scripts is the same as the Methods? Was Scripts ever implemented and tested on the ClickImage?

**Comment by KHerron** [comment]
The code for the Click Control Mouse Up/Down has already been implemented, and is in the current code. 
So, This issue can be closed since the animation for State images should fall under Issue #285.
