### ISSUE TITLE
Change TCP port used by OSA for inter-process communications

### ISSUE THREAD

**Issue by Automate1** [opensourceautomation/Open-Source-Automation#240]
The new non WCF inter-process communications in 0.4.4 is using port 10000.  Suggest a different port is used since 10000 is assigned to other applications.  See comments here
http://www.opensourceautomation.com/phpBB3/osa-using-tcp-port-10000-in-0-4-4-t1110.html

It also would be nice if the user had a way to change the port from the default for instances where it conflicts with some other program using the default port.

**Comment by VaughnRupp** [comment]
Closing as per 044
