### ISSUE TITLE
Add fractional seconds to MySQL timestamp fields

### ISSUE THREAD

**Issue by Automate1** [opensourceautomation/Open-Source-Automation#249]
The factional seconds are specified as the number of digits after the decimal point. MySQL 5.6 and above allows up to 6 digits by defining the field as TIMESTAMP(6). Six digits would be micro seconds which may be overkill for home automation and requires 3 extra bytes of storage. I would suggest either:

hundredths of seconds, TIMESTAMP(2) which only requires one extra byte of storage
or
milliseconds, TIMESTAMP(3) which would require two extra bytes of storage
or
TIMESTAMP(4), a little more precision but still only requires two extra bytes for storage

With this extra resolution we could create a primary key with the the timestamp and object_property_ID.  This would allow eliminating the history_id field to save 4 bytes per record.

**Comment by VaughnRupp** [comment]
Ok, I added this, but even if you only specify 2 digits of fractional time, the formatting commands (%f) still bring up 6 places.    But hey, better too accurate than not enough.   We can work on reducing it to 2 places later if it bothers people.

**Comment by VaughnRupp** [comment]
all logs are now updated.

**Comment by Automate1** [comment]
You can always use .net formatting.  The sting "hh:mm:ss.fff" will display 3 fractional digits.

**Comment by VaughnRupp** [comment]
The server logs were written in a stored proc and passed preformatted to the web page.   I might be able to put the formatting right into the grid, I will give it a try.

**Comment by VaughnRupp** [comment]
OK, I don't want to have to redo it, so I got it to work by taking out the formatting in SQL so .NET could still recognize it, then the grid formatted properly.   Changing everything to 2 digits.
