### ISSUE TITLE
Critial Bug - Null Reference Exception in Screens

### ISSUE THREAD

**Issue by iisfaq** [opensourceautomation/Open-Source-Automation#250]
1) Perform a clean install of server and screens
2) Runs Screens
3) Right click and Create screen (Name: Main,Icon : Switch48x48_off), click Add
4) Right click and select Add Control -> Timer Label
5) Select Weather from the object list
6) Click Add

Application now faults with a null reference exception

---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
 at OSAE.UI.Controls.TimerLabel..ctor(OSAEObject sObj)
 at GUI2.MainWindow.<>c__DisplayClass11.<LoadControl>b__10()
 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
 at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
Clicking OK on null reference exception dialog now shows GUI2 has stopped working dialog.

I tried it with bluetooth module and it did the same as well.

Only fix for me was to delete the database/uninstall/reinstall.

Restarting the screen application just displays the same error immediately and closes down.

Chris

**Comment by VaughnRupp** [comment]
in 0.4.4, there is no error, but the Font field does not have a default on that screen, so I will fix that while testing this issue.

**Comment by VaughnRupp** [comment]
Added default values.   Timer Labels did not get an "Update" overhaul like many other controls though.   I am opening a new ticket to bring it in line.
