### ISSUE TITLE
Add event system to API

### ISSUE THREAD

**Issue by Automate1** [opensourceautomation/Open-Source-Automation#251]
The current OSA API does not have a way for an application to be notified when an event happens in OSA.  Suggest a subscriber/publish mechanism that allows applications to receive an event trigger when something happens in OSA.

Currently the only way to accomplish this is to continually poll the event log table for any changes.

**Comment by VaughnRupp** [comment]
LIB_MYSQLUDF_SYS is the UDF library needed for MySQL to call an external program.   So the trigger on the event_log table would call a small exe that would pass the event to the Service, Screens, etc.

**Comment by VaughnRupp** [comment]
Scripts tied to events provides this functionality now, but maybe not in the way you mean.   Can you provide a couple of examples of the type of event and what the program would do regarding that event, outside of what the scripting system currently provides?   Maybe something similar where we can tied a method from your app to the event so instead of calling a script, it will run a method that gets the info to your program?

**Comment by VaughnRupp** [comment]
I want an event to directly execute a method so a script does not have to set in the middle for really simple triggers.    This method could be to the program that you want to respond to an event.

Not the solution you are looking for, but maybe would address the need?    If so, that is a feature I have been wanting for a while anyways and I can bump it up the list.

**Comment by VaughnRupp** [comment]
After pondering again, I would be creating something very complex like Subscription models to certain events and I don't have a use case to justify it.   I could make a UDP broadcast of all the events as they happen, then the service or plugins could listen to that for particular events, but again, I just can't think of what I need that for.
Any plugin can make any commands it wants, and those commands (methods) can be tied to events now.

So I am closing this until it is requested again with a practical use case that I can implement in one of my plugins for testing, etc.
