### ISSUE TITLE
Add a service locator for the Server

### ISSUE THREAD

**Issue by matthewste** [opensourceautomation/Open-Source-Automation#26]
This is an enhancement, certainly not a priority. But having the ability to locate the server without having to know its IP address. This is more of relevance with the likes of mobile apps to save having to put the server details in.

Likely to use the UDPClient part of the .NET framework to respond to requests for OSA services, although other approaches can be used. It could be further extended to provide information on the UDP response to tell the client what ports to use.

**Comment by VaughnRupp** [comment]
Remote services and managers al have UDP listeners now, and all service and plugin support can be broadcast from the primary service, which handles al methods in the queue.
