### ISSUE TITLE
Bugs in Insteon Plugin

### ISSUE THREAD

**Issue by volfan6415** [opensourceautomation/Open-Source-Automation#272]
As discussed in this thread, http://www.opensourceautomation.com/phpBB3/can%CA%B9t-send-x10-commands-above-address-10-t1250.html, there are some bugs in the insteon plugin code that were impacting X10 commands.

Specifically the code wasn't processing x10 address 10-16
The code wasn't sending x10 off commands; and
the states were not being changed after the plugin executed the methods.  

The changes listed below fix these problems and need to be implemented in the released version

 line 1100 change from:

If method.Address.Length > 2 then

change to

If method.Address.Length > 3 then

line 1201

SerialPLM.Write(data, 0, 4)

should be 

SerialPLM.Write(x10data, 0, 4)

line 1218 needs to be changed from

OSAE.OSAEObjectStateManager.ObjectStateSet(oObject.Name, Command, gAppName)

to 

OSAE.OSAEObjectStateManager.ObjectStateSet(oObject.Name, method.MethodName.ToUpper, gAppName)

**Comment by volfan6415** [comment]
Vaughn - i saw that you fixed one of these bugs (the last one) on your last upload but the other two were not fixed

**Comment by VaughnRupp** [comment]
these issues are shipped in 046
