### ISSUE TITLE
If a slider exists on a screen that is tied to an object without a Level property then an exception is thrown

### ISSUE THREAD

**Issue by mlinnen** [opensourceautomation/Open-Source-Automation#300]
This happens when running the OSAE.Screens program and the program will crash.  The slider value is trying to be set using a Convert.ToUInt16(CurLevel) however the CurLevel is an empty string.  The object I had tied to this control was a z-wave lamp module which probably should have a Level property anyway.

The workaround for this is to add a Level property to the Object Type that is tied to the slider.

**Comment by VaughnRupp** [comment]
I put a try block around it so it won't blow up now, in two places.   I am over hauling the Add StateImage control, so I can disable the slider option if there is no level.   I will figure that out when working that issue though.
