### ISSUE TITLE
Manager need to periodically poll if the services are running.

### ISSUE THREAD

**Issue by bwoodworth** [opensourceautomation/Open-Source-Automation#345]
Occasionally the services crash or are stopped manually outside of the Manger it should represent the current status of the services.

**Comment by VaughnRupp** [comment]
MySQL, and UWS both monitor live and work very well, not sure why the same does not work on the OSA service.   Should be an easy fix.

**Comment by VaughnRupp** [comment]
OSAE service was using a global declaration for the ServiceController, whereas MySQL and UWS used a local instance and worked fine.   I converted the OSAE service to create a new controller when checking and it updates fast now.
