### ISSUE TITLE
Can't Use Installer

### ISSUE THREAD

**Issue by ShiningKnightLight** [opensourceautomation/Open-Source-Automation#364]
I downloaded the latest MySQL (5.7) because the OSA installer couldn't proceed without it. When I set up MySQL I chose a different service name than the default (I chose MySQLService rather than MySQL57) and when I try to run the OSA installer it says that MySQL MUST be installed before proceeding. The service is running though and I can connect to it through MySQL Workbench. I'm on Windows 10 Enterprise.

**Comment by KHerron** [comment]
During the Installation of OSA, you should have been prompted for the MYSQLService password.
Did you enter what you changed it to?

**Comment by ShiningKnightLight** [comment]
That wasn't the issue it turned out. The issue was because I renamed the service to MySQLService from MySQL57 before I ran the installer, and the installer script is looking for those hard coded strings. I changed it back and the installer ran fine, you can go ahead and close the issue. I think coding to find a specific instance of a MySQL service would prove a little more cumbersome with little payoff than just maybe putting a blurb in the install docs that it needs to be named to spec.
