### ISSUE TITLE
WEB UI ability to sort Objects and Object Types by columns

### ISSUE THREAD

**Issue by Automate1** [opensourceautomation/Open-Source-Automation#86]
In the Object and Object Types pages of the WEB UI, add the ability to sort the list by clicking on the header for the corresponding column.

The OSA 0.3.9 GUI had this ability.

**Comment by VaughnRupp** [comment]
Good news is Object page is now done with full 2-way sorting.   I also fixed a bug where previously clicked rows would highlight after a mouse-over.   I am sure a couple more things need to be done to the grid, but this was pretty big.

After the other tickets, I have worked 18 hours today though, and it is 5AM!!! So I hope it is appreciated, but I can't do object_type page tonight, but I will get it done soon.
